import Lenify from "@/components/layout/Lenify";
import "@/styles/globals.scss";

export const metadata = {
  title: "Uncode",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Lenify>
        <body>
          <main>{children}</main>
        </body>
      </Lenify>
    </html>
  );
}
